### ISSUE TITLE
Mirascreen: How did you get the password from the /etc/shadow ??

### ISSUE THREAD

**Issue by niklasarnitz** [gipi/teardown#1]
I am hacking a EZCast with nearly the same Specs and I will attach my /etc/shadow:

root:$1$EIYYGRBK$inOu3EFhrsNF0FzaGDozn.:14610:0:99999:7:::

Can you help me with this one?

**Comment by gipi** [comment]
I used [john the ripper](https://www.openwall.com/john/) with a normal dictionary

**Comment by niklasarnitz** [comment]
coud you link the dicitonary please?

**Comment by gipi** [comment]
My password was easier than your, BTW exists a huge file (like 4.4GB compressed) named breachcompilation.txt, try with that, I can't find a link of the original. Otherwise you can find other wordlists around the web, like https://github.com/danielmiessler/SecLists/tree/master/Passwords.

**Comment by cany748** [comment]
password is: "am2016"
on my "benq qcast mirror" the same password.
![0cteY7WUDt4](https://user-images.githubusercontent.com/30237734/98845898-eddc8c80-2480-11eb-8ed7-69c9d6fbeecb.jpg)


the password was picked using  "john the ripper"

**Comment by hexan86** [comment]
> password is: "am2016"
> on my "benq qcast mirror" the same password.
> ![0cteY7WUDt4](https://user-images.githubusercontent.com/30237734/98845898-eddc8c80-2480-11eb-8ed7-69c9d6fbeecb.jpg)
> 
> the password was picked using "john the ripper"

Can you please describe the commands that you used for john?
I'm trying on my EzCast and I can only obtain "000000" as password 

Tried with john:
```
john.exe --wordlist=dictionary.txt unshadowed.txt 

Warning: detected hash type "md5crypt", but the string is also recognized as "md5crypt-long"
Use the "--format=md5crypt-long" option to force loading these as that type instead
Warning: detected hash type "md5crypt", but the string is also recognized as "md5crypt-opencl"
Use the "--format=md5crypt-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8  
Loaded 1 password hash (md5crypt, crypt(3) $1$ (and variants) [MD5 256/256 AVX2 8x3])
Will run 8 OpenMP threads   Press 'q' or Ctrl-C to abort, almost any other key for status
 000000           (?)
1g 0:00:00:00 DONE (2021-08-06 13:50) 1.231g/s 4729p/s 4729c/s 4729C/s strelka.m..passer2010   
Use the "--show" option to display all of the cracked passwords reliably 
Session completed  
```

The password "am2016" is correct for me too, and after the login I retrieved the shadow file, unshadowed it and obtained again the right hash, but when I try to crack it the result is always "000000".

Knowing your password I even tried:

`hashcat -m 500 -a 3 -o plain.txt unshadowed.txt ?l?l?d?d?d?d`

but the result is always the six zeroes

What am I doing wrong?
