### ISSUE TITLE
LIRC on the Ezcast....RC keystrokes.

### ISSUE THREAD

**Issue by siliconhippy** [gipi/teardown#2]
Saw this GitHub link from CNX Software blog.

Fascinating since I have been discussing my LIRC issue with Hauke, in the comments section, who has been very responsive with his great insights:

https://projects.webvoss.de/2019/03/23/le-potato-media-center-german-iptv-re-revisited/?unapproved=213&moderation-hash=9524af25c6720bad11da0b67ad02aa77#comment-213

My question to you Uber Hacker 😈😈

A. I know you said upfront "installing applications is not possible", but is there a way to find out if the ezcast already has LIRC installed, and if yes, how to access it by the IR receiver keystrokes?

2. If not, is there a way to install LIRC, or alternatively, make ezcast respond to IR ( or 2.4 G wireless or Bluetooth) RC codes?

The whole idea is to build a cheap, modular system, i.e., a good hack.

**Comment by gipi** [comment]
In reality you have access to a shell so I think is possible to install something pretty easily, what I meant is that is not possible to install application "officially".

To upload something using the serial you can use the ``serial_upload.py`` script in the root of the repository, take in mind that has been written like 2 days ago but has worked pretty fine for the MX64. It's very slow but hey, better than nothing :P

Obviously the real solution would be to have some flashing mode but bad enough I haven't found anything relevant yet.

**Comment by siliconhippy** [comment]
Thanks for the quick reply.
How can I quickly check to see if LIRC might be installed already (usually by default)? Does the root password work?

**Comment by gipi** [comment]
If you connect to the serial you have **direct** access to a shell, without any need for a password.

**Comment by siliconhippy** [comment]
😂😐🐵👺😀😀
